name: nix-fmt

on:
  push:
    branches:
      - main
    paths:
      - "*.nix"
      - "**/*.nix"
  pull_request:
    branches:
      - main
    paths:
      - "*.nix"
      - "**/*.nix"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  alejandra:
    runs-on: ubuntu-24.04
    if: github.actor != 'renovate[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: Run Alejandra
        run: nix develop -c alejandra --check .
