name: nsv
on:
  workflow_dispatch:
    inputs:
      projects:
        description: "the project(s) to be tagged, should be separated by whitespace"
        required: true
        type: string

permissions:
  contents: write

jobs:
  nsv:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_NSV }}

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: GPG Import
        env:
          GPG_PRIVATE_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
        run: nix run github:purpleclay/gpg-import

      - name: Tag
        run: nix run github:purpleclay/nsv -- tag --show ${{ inputs.projects }}
