name: typos
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  typos:
    runs-on: ubuntu-24.04
    if: github.actor != 'renovate[bot]'
    name: check spelling
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: Run Typos
        run: nix develop -c typos
