name: x-lib

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The directory containing the Go module"
        required: true
        type: string
    secrets:
      GH_CACHIX:
        required: false

jobs:
  golangci-lint:
    runs-on: ubuntu-24.04
    if: github.actor != 'renovate[bot]'
    name: golangci-lint
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: Lint
        working-directory: ${{ inputs.working-directory }}
        run: nix develop "$GITHUB_WORKSPACE" -c golangci-lint run

  test:
    runs-on: ubuntu-24.04
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: nix develop "$GITHUB_WORKSPACE" -c go test -shuffle=on -race -vet=off ./...

  build:
    runs-on: ubuntu-24.04
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: nix develop "$GITHUB_WORKSPACE" -c go build ./...
